"""Prepare an existing LeRobot v2.1 dataset for LDA training by (re)generating a
gr00t-style ``meta/modality.json`` mapped to the XPolicyLab robot schema.

This adapter deliberately does NOT convert raw HDF5 anymore. RoboDojo already
ships LeRobot datasets (parquet + encoded videos), so the only thing LDA needs
is a ``modality.json`` whose state/action split keys and video keys match the
robot ``*DataConfig`` in ``lda/dataloader/gr00t_lerobot/data_config.py`` (e.g.
``ArxX5DataConfig`` expects ``state.left_arm`` / ``video.cam_head`` ...).

To avoid mutating the shared, read-only source dataset, we materialize a thin
"view" dataset directory under ``policy/LDA_1B/data/<dataset_id>/``:

    data/    -> symlink to <source>/data     (parquet reused as-is)
    videos/  -> symlink to <source>/videos    (encoded videos reused as-is)
    meta/    -> real dir: info.json / episodes*.jsonl / tasks.jsonl / stats.json
                copied from source, plus a freshly written modality.json.

The LeRobot loader writes its own caches (``stats_gr00t.json``,
``steps_*_interval_data_index.pkl``) into ``meta/``; because ``meta/`` is a real
local directory, those writes never touch the shared source dataset.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
from pathlib import Path
from typing import Any, Dict, List


# --- Robot schemas -----------------------------------------------------------
# Each schema mirrors the corresponding *DataConfig in
# lda/dataloader/gr00t_lerobot/data_config.py. ``state``/``action`` blocks map an
# LDA split key -> (start, end) slice of the flat LeRobot ``observation.state`` /
# ``action`` vectors. ``video`` maps an LDA camera key -> a list of candidate
# LeRobot original keys (first existing one in the source info.json wins).

ARX_X5_STATE_ACTION = {
    "left_arm": (0, 6),
    "left_gripper_close": (6, 7),
    "right_arm": (7, 13),
    "right_gripper_close": (13, 14),
}

ROBOT_SCHEMAS: Dict[str, Dict[str, Any]] = {
    "arx_x5": {
        "state": ARX_X5_STATE_ACTION,
        "action": ARX_X5_STATE_ACTION,
        # ArxX5DataConfig uses num_views=1 and only reads video.cam_head.
        "video": {
            "cam_head": ["observation.images.cam_high", "observation.images.cam_head"],
        },
        "annotation": {
            "human.action.task_description": "task_index",
        },
        "expected_dims": {"observation.state": 14, "action": 14},
    },
}
# real_arx_x5 shares the arx_x5 layout.
ROBOT_SCHEMAS["real_arx_x5"] = ROBOT_SCHEMAS["arx_x5"]

# meta files copied verbatim from the source dataset (modality.json is rewritten,
# stats_gr00t.json / step caches are (re)generated by the loader).
META_COPY_FILES = (
    "info.json",
    "episodes.jsonl",
    "episodes_stats.jsonl",
    "tasks.jsonl",
    "stats.json",
)


def _load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as fp:
        return json.load(fp)


def _resolve_video_key(candidates: List[str], features: Dict[str, Any], cam_key: str) -> str:
    for original_key in candidates:
        if original_key in features:
            return original_key
    raise KeyError(
        f"None of the candidate video keys {candidates} for '{cam_key}' exist in "
        f"the source info.json features: {sorted(k for k in features if k.startswith('observation.images'))}"
    )


def _build_modality(schema: Dict[str, Any], info: Dict[str, Any]) -> Dict[str, Any]:
    features = info.get("features", {})

    # Validate flat state/action dimensions against the source dataset.
    for original_key, expected in schema.get("expected_dims", {}).items():
        if original_key not in features:
            raise KeyError(f"Source info.json missing feature '{original_key}'.")
        shape = features[original_key].get("shape", [])
        got = int(shape[0]) if shape else -1
        if got != expected:
            raise ValueError(
                f"Feature '{original_key}' has dim {got} but schema expects {expected}. "
                f"The source dataset does not match this robot schema."
            )

    def block(layout: Dict[str, Any], original_key: str) -> Dict[str, Any]:
        out: Dict[str, Any] = {}
        for subkey, (start, end) in layout.items():
            out[subkey] = {"start": int(start), "end": int(end), "original_key": original_key}
        return out

    modality: Dict[str, Any] = {
        "state": block(schema["state"], "observation.state"),
        "action": block(schema["action"], "action"),
        "video": {},
        "annotation": {},
    }
    for cam_key, candidates in schema["video"].items():
        original_key = _resolve_video_key(candidates, features, cam_key)
        modality["video"][cam_key] = {"original_key": original_key}
    for ann_key, original_key in schema["annotation"].items():
        modality["annotation"][ann_key] = {"original_key": original_key}
    return modality


def _relink(link_path: Path, target: Path) -> None:
    if link_path.is_symlink() or link_path.exists():
        if link_path.is_symlink() or link_path.is_file():
            link_path.unlink()
        else:
            shutil.rmtree(link_path)
    link_path.symlink_to(target)


def prepare(args: argparse.Namespace) -> None:
    lerobot_root = Path(args.lerobot_root).resolve()
    source = (lerobot_root / args.source_repo_id).resolve()
    if not source.is_dir():
        raise FileNotFoundError(f"Source LeRobot dataset not found: {source}")

    source_meta = source / "meta"
    info_path = source_meta / "info.json"
    if not info_path.is_file():
        raise FileNotFoundError(f"Source dataset missing meta/info.json: {info_path}")
    for sub in ("data", "videos"):
        if not (source / sub).is_dir():
            raise FileNotFoundError(f"Source dataset missing '{sub}/': {source / sub}")

    env_cfg_type = args.env_cfg_type
    if env_cfg_type not in ROBOT_SCHEMAS:
        raise KeyError(
            f"No modality schema registered for env_cfg_type='{env_cfg_type}'. "
            f"Known: {sorted(ROBOT_SCHEMAS)}"
        )
    schema = ROBOT_SCHEMAS[env_cfg_type]

    info = _load_json(info_path)
    modality = _build_modality(schema, info)

    output_root = Path(args.output_root).resolve()
    dataset_id = args.dataset_id or args.source_repo_id
    out_dir = output_root / dataset_id
    out_meta = out_dir / "meta"
    out_meta.mkdir(parents=True, exist_ok=True)

    # Reuse heavy artifacts (parquet + videos) via symlink; never copy or mutate.
    _relink(out_dir / "data", source / "data")
    _relink(out_dir / "videos", source / "videos")

    # Copy the small meta files, then write the LDA-specific modality.json.
    for name in META_COPY_FILES:
        src = source_meta / name
        if src.is_file():
            shutil.copy2(src, out_meta / name)

    modality_path = out_meta / "modality.json"
    modality_path.write_text(json.dumps(modality, indent=2), encoding="utf-8")

    # Drop stale loader caches so stats/steps are recomputed against this modality.
    for stale in ("stats_gr00t.json",):
        p = out_meta / stale
        if p.exists():
            p.unlink()
    for cache in out_meta.glob("steps_*_interval_data_index.pkl"):
        cache.unlink()

    video_map = ", ".join(f"{k} -> {v['original_key']}" for k, v in modality["video"].items())
    print(f"[process_data] source     : {source}")
    print(f"[process_data] output     : {out_dir}")
    print(f"[process_data] modality   : {modality_path}")
    print(f"[process_data]   state keys : {list(modality['state'])}")
    print(f"[process_data]   video keys : {video_map}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate an LDA-ready modality.json over an existing LeRobot dataset."
    )
    parser.add_argument(
        "--lerobot-root",
        default=os.environ.get("LDA_LEROBOT_ROOT"),
        help="Root directory containing LeRobot dataset repos (or set env LDA_LEROBOT_ROOT).",
    )
    parser.add_argument(
        "--source-repo-id",
        required=True,
        help="LeRobot dataset folder under --lerobot-root, e.g. RoboDojo_sim_arx-x5_v21_5ep.",
    )
    parser.add_argument(
        "--output-root",
        required=True,
        help="Where the LDA view dataset is written (usually policy/LDA_1B/data).",
    )
    parser.add_argument(
        "--dataset-id",
        default=None,
        help="Output folder name under --output-root (default: source repo id).",
    )
    parser.add_argument(
        "--env-cfg-type",
        required=True,
        help="Robot schema selector, e.g. arx_x5.",
    )
    args = parser.parse_args()
    if not args.lerobot_root:
        parser.error("--lerobot-root is required (or set env LDA_LEROBOT_ROOT).")
    prepare(args)


if __name__ == "__main__":
    main()
