# Basic experiment configuration
policy_name: ACT
protocol: ws
host: localhost
port: null
bench_name: null
task_name: null
ckpt_name: null
env_cfg_type: null
action_type: null
ckpt_setting: null
seed: 0
eval_batch: false

# ACT-specific arguments
kl_weight: 10.0
chunk_size: 50
hidden_dim: 512
dim_feedforward: 3200
temporal_agg: true
device: cuda:0

# DETR parser args
ckpt_dir: null
policy_class: ACT
num_epochs: 6000

# Model training params
position_embedding: sine
lr_backbone: 0.00001
weight_decay: 0.0001
lr: 0.00001
masks: false
dilation: false
backbone: resnet18
nheads: 8
enc_layers: 4
dec_layers: 7
pre_norm: false
dropout: 0.1
camera_names: ["cam_head", "cam_right_wrist", "cam_left_wrist"]
