robotwin_posttrain:
  dataset_names:
  - adjust_bottle-aloha-agilex-demo_clean
  - beat_block_hammer-aloha-agilex-demo_clean
  - blocks_ranking_rgb-aloha-agilex-demo_clean
  - blocks_ranking_size-aloha-agilex-demo_clean
  - click_alarmclock-aloha-agilex-demo_clean
  - click_bell-aloha-agilex-demo_clean
  - dump_bin_bigbin-aloha-agilex-demo_clean
  - grab_roller-aloha-agilex-demo_clean
  - handover_block-aloha-agilex-demo_clean
  - handover_mic-aloha-agilex-demo_clean
  - hanging_mug-aloha-agilex-demo_clean
  - lift_pot-aloha-agilex-demo_clean
  - move_can_pot-aloha-agilex-demo_clean
  - move_pillbottle_pad-aloha-agilex-demo_clean
  - move_playingcard_away-aloha-agilex-demo_clean
  - move_stapler_pad-aloha-agilex-demo_clean
  - open_laptop-aloha-agilex-demo_clean
  - open_microwave-aloha-agilex-demo_clean
  - pick_diverse_bottles-aloha-agilex-demo_clean
  - pick_dual_bottles-aloha-agilex-demo_clean
  - place_a2b_left-aloha-agilex-demo_clean
  - place_a2b_right-aloha-agilex-demo_clean
  - place_bread_basket-aloha-agilex-demo_clean
  - place_bread_skillet-aloha-agilex-demo_clean
  - place_burger_fries-aloha-agilex-demo_clean
  - place_can_basket-aloha-agilex-demo_clean
  - place_cans_plasticbox-aloha-agilex-demo_clean
  - place_container_plate-aloha-agilex-demo_clean
  - place_dual_shoes-aloha-agilex-demo_clean
  - place_empty_cup-aloha-agilex-demo_clean
  - place_fan-aloha-agilex-demo_clean
  - place_mouse_pad-aloha-agilex-demo_clean
  - place_object_basket-aloha-agilex-demo_clean
  - place_object_scale-aloha-agilex-demo_clean
  - place_object_stand-aloha-agilex-demo_clean
  - place_phone_stand-aloha-agilex-demo_clean
  - place_shoe-aloha-agilex-demo_clean
  - press_stapler-aloha-agilex-demo_clean
  - put_bottles_dustbin-aloha-agilex-demo_clean
  - put_object_cabinet-aloha-agilex-demo_clean
  - rotate_qrcode-aloha-agilex-demo_clean
  - scan_object-aloha-agilex-demo_clean
  - shake_bottle-aloha-agilex-demo_clean
  - shake_bottle_horizontally-aloha-agilex-demo_clean
  - stack_blocks_three-aloha-agilex-demo_clean
  - stack_blocks_two-aloha-agilex-demo_clean
  - stack_bowls_three-aloha-agilex-demo_clean
  - stack_bowls_two-aloha-agilex-demo_clean
  - stamp_seal-aloha-agilex-demo_clean
  - turn_switch-aloha-agilex-demo_clean

  data_config_names:
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"
  - "robotwin_qpos"

  embodiment_tags:
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"
  - "new_embodiment"

  sampling_strategy: "step"
  video_backend: "torchvision_av"

  vit_transform_args:
    type: "beingh"
    normalize_type: "imagenet"
    use_color_jitter: true

  frame_step_size:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1

  num_used_episodes_per_task:
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1

  num_used_episodes_per_dataset:
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1

  num_used_frames_per_dataset:
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1

  weight: 1
