#!/usr/bin/env python3
"""Run offline ACT inference on expert observations and compare action chunks.

Evaluation performed by this script
-----------------------------------
For a sampled frame ``t`` in one expert episode:

1. Read the expert observation at ``t``:
   ``state[t]`` plus the three synchronized camera images.
2. Normalize those inputs with the exact mean/std tensors saved during training.
3. Ask ACT for a 50-step action chunk (``chunk_size=50``):
   ``predicted_action[t:t+50]``.
4. Convert that normalized prediction back to the dataset's original action
   units with the saved action mean/std.
5. Compare it with expert actions using three horizons:
   - first step: immediate-action accuracy;
   - first 10 steps: deployment-relevant window (``n_action_steps=10``);
   - all 50 steps: diagnostic long-horizon chunk accuracy.

ACT predicts 50 steps per query, but Isaac Sim should execute only the first 10
before querying the policy again with a new observation. Therefore the 10-step
MAE is the primary offline metric for the configured deployment behavior.

The generated time-series plots show *actual action values in the dataset's
original units*, not MAE. Each plotted ACT value is the first action of the
chunk predicted at that sampled observation. MAE values are written separately
to ``summary.json`` and ``samples.csv``.

This is teacher-observation/offline evaluation: every model query receives an
observation from the expert trajectory. It does not test recovery after ACT's
own actions move Isaac Sim away from that trajectory.
"""

from __future__ import annotations

import argparse
import csv
import inspect
import json
import types
from pathlib import Path

import numpy as np
import torch


CAMERAS = (
    "observation.images.cam_high",
    "observation.images.cam_left_wrist",
    "observation.images.cam_right_wrist",
)

ACTION_NAMES = (
    "l_x", "l_y", "l_z", "l_w", "l_wx", "l_wy", "l_wz", "l_g",
    "r_x", "r_y", "r_z", "r_w", "r_wx", "r_wy", "r_wz", "r_g",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=Path, default=Path("act/model.ckpt"))
    parser.add_argument("--dataset", type=Path, default=Path("data/lerobot_v30_ee"))
    parser.add_argument(
        "--episode",
        type=int,
        default=None,
        help="Episode to analyze. With --split-path it must belong to --split.",
    )
    parser.add_argument(
        "--split-path",
        type=Path,
        help="Optional train/val split JSON generated by act/split_episodes.py.",
    )
    parser.add_argument(
        "--split",
        choices=("train", "val"),
        default="val",
        help="Allowed split when --split-path is provided (default: val).",
    )
    parser.add_argument(
        "--stride",
        type=int,
        default=25,
        help="Run one ACT query every N frames (default: 25, i.e. 1 second)",
    )
    parser.add_argument(
        "--max-samples",
        type=int,
        default=0,
        help="Maximum sampled observations; 0 means no limit",
    )
    parser.add_argument("--output-dir", type=Path, default=Path("outputs/act_analysis"))
    parser.add_argument("--video-backend", default="pyav")
    return parser.parse_args()


def load_policy(checkpoint: Path):
    """Load the ACT network and verify checkpoint/model compatibility.

    Compatibility checks performed here:

    1. ``torch.load`` verifies that the checkpoint file is readable.
    2. The serialized config is decoded and used to construct the locally
       installed LeRobot ACT implementation.
    3. ``load_state_dict(..., strict=True)`` is the decisive architecture and
       weight compatibility check: every parameter name and tensor shape must
       match, with no missing or unexpected model tensors.

    In practice, steps 2 and 3 form one check. If the local code interprets an
    architecture-affecting config value differently, strict loading normally
    fails because the resulting parameter names or shapes differ.

    Important boundary: strict state-dict loading cannot validate settings that
    do not change model parameter names/shapes, such as feature semantics,
    camera ordering, normalization behavior, ``n_action_steps``, coordinate
    systems, quaternion conventions, or gripper direction. Those are separate
    preprocessing and Isaac-Sim interface checks.
    """
    # LeRobot 0.4.4 probes torch.xpu, which Torch 2.2 on this Mac lacks.
    if not hasattr(torch, "xpu"):
        torch.xpu = types.SimpleNamespace(is_available=lambda: False)

    from lerobot.configs.types import FeatureType, NormalizationMode, PolicyFeature
    from lerobot.policies.act.configuration_act import ACTConfig
    from lerobot.policies.act.modeling_act import ACTPolicy

    # Loading the file only proves that the checkpoint is readable. We still
    # need to reconstruct the ACT architecture and strictly match every model
    # tensor below.
    saved = torch.load(checkpoint, map_location="cpu", weights_only=False)
    raw_config = dict(saved["config"])

    # A checkpoint stores configuration *values*, but not the Python
    # implementation of ACTConfig/ACTPolicy. Training used LeRobot 0.6.0 while
    # this Mac currently has 0.4.4, so retain only fields understood locally
    # and explicitly decode serialized strings back to typed config objects.
    # This conversion is preparation for the decisive strict=True check below,
    # rather than an independent proof of compatibility.
    valid_fields = set(inspect.signature(ACTConfig).parameters)
    config = {key: value for key, value in raw_config.items() if key in valid_fields}
    config["device"] = "cpu"
    # The complete trained backbone is already in the checkpoint; disabling
    # pretrained weights also prevents an unnecessary ImageNet download.
    config["pretrained_backbone_weights"] = None
    config["input_features"] = {
        key: PolicyFeature(type=FeatureType[value["type"]], shape=tuple(value["shape"]))
        for key, value in config["input_features"].items()
    }
    config["output_features"] = {
        key: PolicyFeature(type=FeatureType[value["type"]], shape=tuple(value["shape"]))
        for key, value in config["output_features"].items()
    }
    config["normalization_mapping"] = {
        FeatureType[key]: NormalizationMode(value)
        for key, value in config["normalization_mapping"].items()
    }

    # This step executes the locally installed LeRobot code to construct the
    # network described by the serialized configuration values.
    policy = ACTPolicy(ACTConfig(**config))
    model_state = {
        key: value
        for key, value in saved["state_dict"].items()
        if key.startswith("model.")
    }
    # Decisive model compatibility check:
    # - no model parameter may be missing;
    # - no unexpected model parameter may remain;
    # - every same-named parameter must have exactly the expected tensor shape.
    #
    # This validates the parameterized network structure and trained weights,
    # but not preprocessing or the physical meaning of the 16 input/output
    # dimensions.
    policy.load_state_dict(model_state, strict=True)
    policy.eval()
    return policy, saved["state_dict"]


def normalize(value: torch.Tensor, stats: dict[str, torch.Tensor], key: str) -> torch.Tensor:
    """Rebuild the training preprocessor: original units -> normalized units."""
    std = stats[f"{key}.std"].clamp_min(1e-8)
    return (value - stats[f"{key}.mean"]) / std


def unnormalize(value: torch.Tensor, stats: dict[str, torch.Tensor], key: str) -> torch.Tensor:
    """Rebuild the training postprocessor: normalized units -> original units."""
    return value * stats[f"{key}.std"] + stats[f"{key}.mean"]


def make_batch(sample: dict, stats: dict[str, torch.Tensor]) -> dict[str, torch.Tensor]:
    # ACT was trained on normalized state and RGB tensors. Feeding raw values
    # would still run successfully but would produce semantically invalid output.
    #
    # This offline script reads the same training dataset, so feature semantics
    # already match by construction. Isaac Sim deployment needs an additional
    # adapter-level check outside this function: camera order/RGB convention,
    # left-right ordering, coordinate frame, quaternion layout, absolute-action
    # meaning, and gripper range/direction must match the training dataset.
    batch = {
        "observation.state": normalize(
            sample["observation.state"].float(), stats, "observation.state"
        ).unsqueeze(0)
    }
    for camera in CAMERAS:
        batch[camera] = normalize(sample[camera].float(), stats, camera).unsqueeze(0)
    return batch


def save_plots(
    output: Path,
    frame_indices: np.ndarray,
    expert: np.ndarray,
    predicted: np.ndarray,
) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    groups = {
        "left_position": range(0, 3),
        "left_rotation": range(3, 7),
        "left_gripper": range(7, 8),
        "right_position": range(8, 11),
        "right_rotation": range(11, 15),
        "right_gripper": range(15, 16),
    }
    for group_name, dimensions in groups.items():
        dimensions = list(dimensions)
        figure, axes = plt.subplots(
            len(dimensions), 1, figsize=(12, 2.6 * len(dimensions)), sharex=True
        )
        axes = np.atleast_1d(axes)
        for axis, dimension in zip(axes, dimensions, strict=True):
            axis.plot(frame_indices, expert[:, dimension], label="expert", linewidth=1.8)
            axis.plot(
                frame_indices,
                predicted[:, dimension],
                label="ACT predicted",
                linestyle="--",
                linewidth=1.5,
            )
            axis.set_ylabel(ACTION_NAMES[dimension])
            axis.grid(alpha=0.25)
        axes[0].legend()
        axes[-1].set_xlabel("frame index")
        figure.tight_layout()
        figure.savefig(output / f"{group_name}.png", dpi=150)
        plt.close(figure)


def resolve_episode(args: argparse.Namespace) -> int:
    """Resolve and validate an episode against the optional split manifest."""

    if args.split_path is None:
        return 0 if args.episode is None else args.episode

    with args.split_path.resolve().open(encoding="utf-8") as file:
        split_manifest = json.load(file)
    allowed = [int(index) for index in split_manifest[args.split]]
    if not allowed:
        raise ValueError(f"Split {args.split!r} contains no episodes")

    episode = allowed[0] if args.episode is None else args.episode
    if episode not in set(allowed):
        raise ValueError(
            f"Episode {episode} does not belong to split {args.split!r} "
            f"in {args.split_path}"
        )
    return episode


def main() -> None:
    args = parse_args()
    if args.stride <= 0:
        raise ValueError("--stride must be positive")
    episode = resolve_episode(args)

    from lerobot.datasets.lerobot_dataset import LeRobotDataset

    policy, stats = load_policy(args.checkpoint.resolve())
    dataset = LeRobotDataset(
        repo_id=args.dataset.name,
        root=args.dataset.resolve(),
        episodes=[episode],
        video_backend=args.video_backend,
    )

    # Sparse sampling keeps CPU analysis practical. With stride=25 at 25 FPS,
    # ACT is queried once per second, always using an expert observation.
    sample_indices = list(range(0, len(dataset), args.stride))
    if args.max_samples:
        sample_indices = sample_indices[: args.max_samples]

    rows: list[dict[str, float | int]] = []
    first_expert: list[np.ndarray] = []
    first_predicted: list[np.ndarray] = []
    frame_indices: list[int] = []
    execution_window_maes: list[float] = []
    full_chunk_maes: list[float] = []

    print(
        f"Episode {episode}: {len(dataset)} frames; "
        f"running {len(sample_indices)} ACT queries on CPU"
    )
    for number, index in enumerate(sample_indices, start=1):
        # Expert observation at frame t. The sample also contains expert
        # action[t], but that action is not passed into ACT at inference time.
        sample = dataset[index]
        batch = make_batch(sample, stats)
        with torch.inference_mode():
            # Shape: [50, 16] after removing the batch dimension. These values
            # are still in the normalized action space used during training.
            normalized_chunk = policy.predict_action_chunk(batch)[0].cpu()
        # Return predictions to the same original units as dataset["action"].
        predicted_chunk = unnormalize(normalized_chunk, stats, "action").numpy()

        # Read expert future actions without decoding their camera frames.
        # Near the episode end, compare only the remaining valid horizon.
        remaining = min(policy.config.chunk_size, len(dataset) - index)
        expert_chunk = np.asarray(
            dataset.hf_dataset[index : index + remaining]["action"], dtype=np.float32
        )
        predicted_valid = predicted_chunk[:remaining]
        absolute_error = np.abs(predicted_valid - expert_chunk)

        expert_first = expert_chunk[0]
        predicted_first = predicted_valid[0]
        # First-step MAE compares predicted_action[t] with expert_action[t].
        # Execution-window MAE compares the first n_action_steps (10), matching
        # how many queued actions Isaac Sim will execute before the next query.
        # Full-chunk MAE compares all 50 predicted steps as a diagnostic only.
        first_mae = float(np.mean(np.abs(predicted_first - expert_first)))
        execution_steps = min(policy.config.n_action_steps, remaining)
        execution_window_mae = float(absolute_error[:execution_steps].mean())
        full_chunk_mae = float(absolute_error.mean())
        execution_window_maes.append(execution_window_mae)
        full_chunk_maes.append(full_chunk_mae)
        frame_index = int(sample["frame_index"])

        row: dict[str, float | int] = {
            "frame_index": frame_index,
            "first_action_mae": first_mae,
            "execution_window_steps": execution_steps,
            "execution_window_mae": execution_window_mae,
            "full_chunk_steps": remaining,
            "full_chunk_mae": full_chunk_mae,
        }
        for dimension, name in enumerate(ACTION_NAMES):
            row[f"{name}_abs_error"] = float(abs(predicted_first[dimension] - expert_first[dimension]))
        rows.append(row)
        frame_indices.append(frame_index)
        first_expert.append(expert_first)
        first_predicted.append(predicted_first)
        print(
            f"[{number:>3}/{len(sample_indices)}] frame={frame_index:>4} "
            f"first={first_mae:.5f} exec{execution_steps}={execution_window_mae:.5f} "
            f"chunk{remaining}={full_chunk_mae:.5f}"
        )

    output = args.output_dir.resolve() / f"episode_{episode:04d}"
    output.mkdir(parents=True, exist_ok=True)
    with (output / "samples.csv").open("w", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)

    expert_array = np.stack(first_expert)
    predicted_array = np.stack(first_predicted)
    per_dimension_mae = np.mean(np.abs(predicted_array - expert_array), axis=0)
    summary = {
        "episode": episode,
        "split": args.split if args.split_path is not None else None,
        "split_path": str(args.split_path.resolve()) if args.split_path is not None else None,
        "episode_frames": len(dataset),
        "sample_count": len(rows),
        "stride": args.stride,
        "first_action_mae": float(np.mean(np.abs(predicted_array - expert_array))),
        "n_action_steps": policy.config.n_action_steps,
        "execution_window_mae": float(np.mean(execution_window_maes)),
        "chunk_size": policy.config.chunk_size,
        "full_chunk_mae": float(np.mean(full_chunk_maes)),
        "per_dimension_mae": {
            name: float(value)
            for name, value in zip(ACTION_NAMES, per_dimension_mae, strict=True)
        },
    }
    (output / "summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False) + "\n"
    )
    save_plots(
        output,
        np.asarray(frame_indices),
        expert_array,
        predicted_array,
    )
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    print(f"Saved analysis: {output}")


if __name__ == "__main__":
    main()
