image_augmentation:
  enable: true
  enable_random_erasing: true
  enable_sharpening: true
  augmentation_prob: 0.5

lerobot:
  - path: /path/to/lerobot/RoboDojo_sim_arx-x5_v21
    weight: 1.0
    normalization_type: bounds
    use_num_images: 3
    image_augmentation: true
