# model_type for RLinf registry (Dexbotic bridge).
model_type: "dexbotic_dm0"

model_path: "/path/to/model/dexbotic_dm0"

precision: null

num_action_chunks: 50
action_dim: 7

is_lora: False
lora_rank: 32

use_proprio: True
num_steps: 10
add_value_head: True

safe_get_logprob: False
chunk_critic_input: True
noise_anneal: False
joint_logprob: False
value_after_vlm: False

dexbotic:
  num_images_in_input: 2
  noise_level: 0.5
  action_chunk: ${actor.model.num_action_chunks}
  num_steps: ${actor.model.num_steps}
  train_expert_only: True
  action_env_dim: ${actor.model.action_dim}
  noise_method: "flow_sde"
  add_value_head: ${actor.model.add_value_head}
  detach_critic_input: False
