Rigid:
  -
    common:
      xlim: [[-0.30, -0.05], [0.05, 0.30]]
      ylim: [-0.20, 0.05]
      rotate_rand: False
      rotate_deg: 0
      relative_plane: "Table"
      qpos: [1, 0, 0, 0]
      margin: 0.04

    category:
      -
        name: "wuliangye"
        index: [0]

    select_mode:
      nums: [1]
      mode: "unique"
      label: ["bottle"]

  -
    common:
      xlim: [-0.05, 0.05]
      ylim: [-0.1, 0.0]
      rotate_rand: False
      rotate_deg: 0
      relative_plane: "Table"
      qpos: [1, 0, 0, 0]
      margin: 0.04

    category:
      -
        name: "mug"
        index: [15, 16]
      -
        name: "goblet"
        index: [6]
        
    select_mode:
      nums: [1]
      mode: "unique"
      label: ["cup"]

Fluid:
  -
    common:
      xlim: [0.0, 0.0]
      ylim: [0.0, 0.0]
      zlim: [-0.133, -0.133]
      rotate_rand: False
      relative_plane: "bottle"
      check_mode: "enforce"

    category:
      -
        name: "wuliangye"
        index: [0]

    select_mode:
      nums: [1]
      mode: "unique"
      label: ["wine"]
