Rigid:
  -
    common:
      xlim: [-0.45, 0.45]
      ylim: [-0.25, -0.1]
      rotate_deg: 360
      rotate_rand: True
      relative_plane: "Table"

    category:
      - 
        name: "t"
        index: [0]
    
    select_mode:
      nums: 1
      mode: "allow_duplicate"
      label: ["t"]
      
Geometry:
  -
    common:
      xlim: [-0.45, 0.45]
      ylim: [-0.25, -0.1]
      rotate_deg: 360
      rotate_rand: True
      relative_plane: "Table"

    category:
      - 
        name: "t_cushion"
    
    select_mode:
      nums: 1
      mode: "allow_duplicate"
      label: ["target_t"]
