TASK_INFO = {
    "open_the_drawer": {
        "task": "open the drawer",
        "rot_type": "euler",
        "robot_type": "ARX5",
        "action_type": "leftpos",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "water_potted_plant": {
        "task": "water the potted plant using the kettle",
        "rot_type": "euler",
        "robot_type": "ARX5",
        "action_type": "leftpos",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "sort_electronic_products": {
        "task": "classify the four electronic products on the table and place them into the corresponding transparent baskets",
        "rot_type": "euler",
        "robot_type": "ARX5",
        "action_type": "leftpos",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "search_green_boxes": {
        "task": "search through the stack of blocks for the green blocks and place it into the yellow box",
        "rot_type": "euler",
        "robot_type": "ARX5",
        "action_type": "leftpos",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "arrange_paper_cups": {
        "task": "stack the four paper cups on top of the paper cup closest to the shelf one by one and place the stacked cups on the shelf",
        "rot_type": "euler",
        "robot_type": "ARX5",
        "action_type": "leftpos",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "arrange_flowers": {
        "task": "insert the three flowers on the table into the vase one by one",
        "rot_type": "euler",
        "robot_type": "ARX5",
        "action_type": "leftpos",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "fold_dishcloth": {
        "task": "fold the dishcloth in half twice, then place it in the position slightly to the front and left",
        "rot_type": "euler",
        "robot_type": "ARX5",
        "action_type": "leftpos",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "place_shoes_on_rack": {
        "task": "place these shoes on the shoe rack",
        "rot_type": "euler",
        "robot_type": "ARX5",
        "action_type": "leftpos",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "put_cup_on_coaster": {
        "task": "place the cup on the coaster",
        "rot_type": "euler",
        "robot_type": "ARX5",
        "action_type": "leftpos",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "turn_on_light_switch": {
        "task": "turn on the light switch",
        "rot_type": "euler",
        "robot_type": "ARX5",
        "action_type": "leftpos",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "wipe_the_table": {
        "task": "pull out a tissue, wipe the stains on the table clean, and then discard the tissue into the trash bin",
        "rot_type": "euler",
        "robot_type": "ARX5",
        "action_type": "leftpos",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "stack_bowls": {
        "task": "stack the two smaller bowls on top of the largest bowl one by one.",
        "rot_type": "quat",
        "robot_type": "aloha",
        "action_type": "pos",
        "observation.images.cam_high": "high",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "right_hand",
    },
    "stick_tape_to_box": {
        "task": "tear off a piece of clear tape and stick it onto the metal box",
        "rot_type": "quat",
        "robot_type": "aloha",
        "action_type": "pos",
        "observation.images.cam_high": "high",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "right_hand",
    },
    "sweep_the_rubbish": {
        "task": "sweep the trash into the dustpan using a broom",
        "rot_type": "quat",
        "robot_type": "aloha",
        "action_type": "pos",
        "observation.images.cam_high": "high",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "right_hand",
    },
    "turn_on_faucet": {
        "task": "grasp the faucet switch and turn it on",
        "rot_type": "quat",
        "robot_type": "aloha",
        "action_type": "pos",
        "observation.images.cam_high": "high",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "right_hand",
    },
    "scan_QR_code": {
        "task": "scan the QR code on the medicine box using the scanner",
        "rot_type": "quat",
        "robot_type": "aloha",
        "action_type": "pos",
        "observation.images.cam_high": "high",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "right_hand",
    },
    "put_pen_into_pencil_case": {
        "task": "place the pen on the table into the pencil case",
        "rot_type": "quat",
        "robot_type": "aloha",
        "action_type": "pos",
        "observation.images.cam_high": "high",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "right_hand",
    },
    "put_opener_in_drawer": {
        "task": "place the can opener into the right-hand drawer",
        "rot_type": "quat",
        "robot_type": "aloha",
        "action_type": "pos",
        "observation.images.cam_high": "high",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "right_hand",
    },
    "pour_fries_into_plate": {
        "task": "open the box lid and pour the chips from the box onto the plate.",
        "rot_type": "quat",
        "robot_type": "aloha",
        "action_type": "pos",
        "observation.images.cam_high": "high",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "right_hand",
    },
    "plug_in_network_cable": {
        "task": "Insert the RJ45 connector of the Ethernet cable into the host.",
        "rot_type": "quat",
        "robot_type": "aloha",
        "action_type": "pos",
        "observation.images.cam_high": "high",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "right_hand",
    },
    "make_vegetarian_sandwich": {
        "task": "make a vegetable sandwich",
        "rot_type": "quat",
        "robot_type": "aloha",
        "action_type": "pos",
        "observation.images.cam_high": "high",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "right_hand",
    },
    "clean_dining_table": {
        "task": "place all the trash into the green trash bin, and put the dishes into the transparent basket",
        "rot_type": "quat",
        "robot_type": "aloha",
        "action_type": "pos",
        "observation.images.cam_high": "high",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "right_hand",
    },
    "move_objects_into_box": {
        "task": "place all the clutter on the desk into the white box",
        "rot_type": "quat",
        "robot_type": "Franka",
        "action_type": "leftpos",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "press_three_buttons": {
        "task": "press the pink, blue, and green buttons in sequence",
        "rot_type": "quat",
        "robot_type": "Franka",
        "action_type": "leftpos",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
        "sub_task_pool": [
            "Press the pink button.",
            "Press the blue button.",
            "Press the green button.",
            "Reset the arm.",
        ]
    },
    "arrange_fruits_in_basket": {
        "task": "Place the four fruits into the nearby basket one by one",
        "rot_type": "quat",
        "robot_type": "UR5",
        "action_type": "leftjoint",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "hang_toothbrush_cup": {
        "task": "hang the orange toothbrush cup on the cup holder",
        "rot_type": "quat",
        "robot_type": "UR5",
        "action_type": "leftjoint",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "set_the_plates": {
        "task": "place the three plates onto the plate rack one by one",
        "rot_type": "quat",
        "robot_type": "UR5",
        "action_type": "leftjoint",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "shred_scrap_paper": {
        "task": "place the white paper on the shelf into the shredder for shredding",
        "rot_type": "quat",
        "robot_type": "UR5",
        "action_type": "leftjoint",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "sort_books": {
        "task": "place the three books on the shelf into the corresponding book sections of the black bookshelf",
        "rot_type": "quat",
        "robot_type": "UR5",
        "action_type": "leftjoint",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
    "stack_color_blocks": {
        "task": "stack the yellow block on top of the orange block",
        "rot_type": "quat",
        "robot_type": "UR5",
        "action_type": "leftjoint",
        "observation.images.cam_high": "right_hand",
        "observation.images.cam_left_wrist": "left_hand",
        "observation.images.cam_right_wrist": "high",
    },
}

# Tasks that should use a smaller chunk size by default
TASKS_USE_LESS_CHUNK_SIZE = ["move_objects_into_box"]
# Tasks that need apply gripper binarization
TASTS_APPLY_GRIPPER_BINARIZATION = {"move_objects_into_box": 0.055}
